apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: adoptme
  template:
    metadata:
      labels:
        app: adoptme
    spec:
      containers:
      - name: adoptme
        image: fedco/adoptme:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://gutierrezfedericog:ZGu2Q70OsMrmWJL9@cluster0.yex3ufx.mongodb.net/backend3?retryWrites=true&w=majority&appName=Cluster0"
---
apiVersion: v1
kind: Service
metadata: 
  name: adoptme-service
spec:
  selector:
    app: adoptme
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer